URL = "http://127.0.0.1:8000/validate"

scenarios = [
    {
        "name": "Allow: wire approval within AI mandate",
        "payload": {
            "decision_id": "wire-1001",
            "actor_id": "ai_agent_1",
            "actor_role": "ai_agent",
            "action": "approve_wire",
            "resource": "customer_account_8831",
            "amount": 5000,
            "risk_score": 0.22,
            "evidence_score": 0.93,
            "jurisdiction": "US",
            "business_unit": "consumer_banking",
            "override_requested": False,
            "review_case_id": "WIRE-CASE-1001",
            "context": {
                "customer_authentication_match": True,
                "account_status_clear": True,
                "sanctions_screen_complete": True,
                "fraud_model_score_present": True,
                "first_time_beneficiary": False,
                "out_of_pattern_transaction": False,
                "sanctions_hit": False,
            },
        },
    },
    {
        "name": "Escalate: first-time beneficiary wire",
        "payload": {
            "decision_id": "wire-1002",
            "actor_id": "ai_agent_1",
            "actor_role": "ai_agent",
            "action": "approve_wire",
            "resource": "customer_account_8831",
            "amount": 4500,
            "risk_score": 0.27,
            "evidence_score": 0.91,
            "jurisdiction": "US",
            "business_unit": "consumer_banking",
            "override_requested": False,
            "review_case_id": "WIRE-CASE-1002",
            "context": {
                "customer_authentication_match": True,
                "account_status_clear": True,
                "sanctions_screen_complete": True,
                "fraud_model_score_present": True,
                "first_time_beneficiary": True,
                "out_of_pattern_transaction": False,
                "sanctions_hit": False,
            },
        },
    },
    {
        "name": "Refuse: sanctions hit on wire",
        "payload": {
            "decision_id": "wire-1003",
            "actor_id": "ai_agent_1",
            "actor_role": "ai_agent",
            "action": "approve_wire",
            "resource": "customer_account_8831",
            "amount": 2200,
            "risk_score": 0.35,
            "evidence_score": 0.89,
            "jurisdiction": "US",
            "business_unit": "consumer_banking",
            "override_requested": False,
            "review_case_id": "WIRE-CASE-1003",
            "context": {
                "customer_authentication_match": True,
                "account_status_clear": True,
                "sanctions_screen_complete": True,
                "fraud_model_score_present": True,
                "first_time_beneficiary": False,
                "out_of_pattern_transaction": False,
                "sanctions_hit": True,
            },
        },
    },
    {
        "name": "Allow: fraud analyst releases hold",
        "payload": {
            "decision_id": "fraud-2001",
            "actor_id": "fraud_analyst_1",
            "actor_role": "fraud_analyst",
            "action": "release_fraud_hold",
            "resource": "deposit_account_1029",
            "amount": None,
            "risk_score": 0.28,
            "evidence_score": 0.91,
            "jurisdiction": "US",
            "business_unit": "consumer_banking",
            "override_requested": False,
            "review_case_id": "FRAUD-CASE-2001",
            "context": {
                "account_id": "deposit_account_1029",
                "hold_reason": "card_not_present_review",
                "customer_contact_completed_or_waived": True,
                "fraud_alert_history_present": True,
                "transaction_graph_evaluated": True,
                "account_takeover_signal_checked": True,
                "mule_network_signal": False,
                "linked_account_exposure": False,
                "confirmed_account_takeover": False,
                "active_law_enforcement_hold": False,
            },
        },
    },
    {
        "name": "Escalate: linked account exposure on fraud case",
        "payload": {
            "decision_id": "fraud-2002",
            "actor_id": "fraud_analyst_1",
            "actor_role": "fraud_analyst",
            "action": "release_fraud_hold",
            "resource": "deposit_account_1042",
            "amount": None,
            "risk_score": 0.41,
            "evidence_score": 0.89,
            "jurisdiction": "US",
            "business_unit": "consumer_banking",
            "override_requested": False,
            "review_case_id": "FRAUD-CASE-2002",
            "context": {
                "account_id": "deposit_account_1042",
                "hold_reason": "peer_to_peer_review",
                "customer_contact_completed_or_waived": True,
                "fraud_alert_history_present": True,
                "transaction_graph_evaluated": True,
                "account_takeover_signal_checked": True,
                "mule_network_signal": False,
                "linked_account_exposure": True,
                "confirmed_account_takeover": False,
                "active_law_enforcement_hold": False,
            },
        },
    },
    {
        "name": "Refuse: confirmed takeover fraud case",
        "payload": {
            "decision_id": "fraud-2003",
            "actor_id": "fraud_analyst_1",
            "actor_role": "fraud_analyst",
            "action": "release_fraud_hold",
            "resource": "deposit_account_1058",
            "amount": None,
            "risk_score": 0.74,
            "evidence_score": 0.92,
            "jurisdiction": "US",
            "business_unit": "consumer_banking",
            "override_requested": False,
            "review_case_id": "FRAUD-CASE-2003",
            "context": {
                "account_id": "deposit_account_1058",
                "hold_reason": "account_takeover_review",
                "customer_contact_completed_or_waived": True,
                "fraud_alert_history_present": True,
                "transaction_graph_evaluated": True,
                "account_takeover_signal_checked": True,
                "mule_network_signal": False,
                "linked_account_exposure": False,
                "confirmed_account_takeover": True,
                "active_law_enforcement_hold": False,
            },
        },
    },
    {
        "name": "Allow: underwriting analyst approves modest increase",
        "payload": {
            "decision_id": "credit-3001",
            "actor_id": "underwriting_analyst_1",
            "actor_role": "underwriting_analyst",
            "action": "approve_credit_increase",
            "resource": "credit_account_4431",
            "amount": 3000,
            "risk_score": 0.31,
            "evidence_score": 0.90,
            "jurisdiction": "US",
            "business_unit": "cards",
            "override_requested": False,
            "review_case_id": "CREDIT-CASE-3001",
            "context": {
                "customer_id": "cust_4431",
                "requested_increase": 3000,
                "affordability_result": "pass",
                "bureau_pull_current": True,
                "affordability_assessment_complete": True,
                "internal_delinquency_review_complete": True,
                "income_signal_present_or_verified": True,
                "thin_file_customer": False,
                "income_variability_high": False,
                "active_bankruptcy_signal": False,
                "30dpd_in_last_6_months": False,
                "fair_lending_check_failed": False,
            },
        },
    },
    {
        "name": "Escalate: thin file credit increase",
        "payload": {
            "decision_id": "credit-3002",
            "actor_id": "underwriting_analyst_1",
            "actor_role": "underwriting_analyst",
            "action": "approve_credit_increase",
            "resource": "credit_account_4522",
            "amount": 3200,
            "risk_score": 0.33,
            "evidence_score": 0.88,
            "jurisdiction": "US",
            "business_unit": "cards",
            "override_requested": False,
            "review_case_id": "CREDIT-CASE-3002",
            "context": {
                "customer_id": "cust_4522",
                "requested_increase": 3200,
                "affordability_result": "pass",
                "bureau_pull_current": True,
                "affordability_assessment_complete": True,
                "internal_delinquency_review_complete": True,
                "income_signal_present_or_verified": True,
                "thin_file_customer": True,
                "income_variability_high": False,
                "active_bankruptcy_signal": False,
                "30dpd_in_last_6_months": False,
                "fair_lending_check_failed": False,
            },
        },
    },
    {
        "name": "Refuse: fair lending control failed",
        "payload": {
            "decision_id": "credit-3003",
            "actor_id": "underwriting_analyst_1",
            "actor_role": "underwriting_analyst",
            "action": "approve_credit_increase",
            "resource": "credit_account_4688",
            "amount": 2800,
            "risk_score": 0.29,
            "evidence_score": 0.91,
            "jurisdiction": "US",
            "business_unit": "cards",
            "override_requested": False,
            "review_case_id": "CREDIT-CASE-3003",
            "context": {
                "customer_id": "cust_4688",
                "requested_increase": 2800,
                "affordability_result": "manual_review",
                "bureau_pull_current": True,
                "affordability_assessment_complete": True,
                "internal_delinquency_review_complete": True,
                "income_signal_present_or_verified": True,
                "thin_file_customer": False,
                "income_variability_high": False,
                "active_bankruptcy_signal": False,
                "30dpd_in_last_6_months": False,
                "fair_lending_check_failed": True,
            },
        },
    },
    {
        "name": "Allow: KYC analyst clears case",
        "payload": {
            "decision_id": "kyc-4001",
            "actor_id": "kyc_analyst_1",
            "actor_role": "kyc_analyst",
            "action": "clear_kyc_case",
            "resource": "customer_profile_7711",
            "amount": None,
            "risk_score": 0.18,
            "evidence_score": 0.89,
            "jurisdiction": "US",
            "business_unit": "retail_banking",
            "override_requested": False,
            "review_case_id": "KYC-CASE-4001",
            "context": {
                "customer_id": "cust_7711",
                "screening_status": "clear",
                "identity_document_validated": True,
                "customer_profile_refreshed": True,
                "screening_results_current": True,
                "beneficial_owner_review_complete_if_required": True,
                "politically_exposed_person": False,
                "jurisdiction_risk_high": False,
                "ownership_structure_complex": False,
                "screening_match_unresolved": False,
                "identity_mismatch": False,
            },
        },
    },
    {
        "name": "Escalate: PEP KYC case",
        "payload": {
            "decision_id": "kyc-4002",
            "actor_id": "kyc_analyst_1",
            "actor_role": "kyc_analyst",
            "action": "clear_kyc_case",
            "resource": "customer_profile_7821",
            "amount": None,
            "risk_score": 0.26,
            "evidence_score": 0.88,
            "jurisdiction": "US",
            "business_unit": "retail_banking",
            "override_requested": False,
            "review_case_id": "KYC-CASE-4002",
            "context": {
                "customer_id": "cust_7821",
                "screening_status": "clear",
                "identity_document_validated": True,
                "customer_profile_refreshed": True,
                "screening_results_current": True,
                "beneficial_owner_review_complete_if_required": True,
                "politically_exposed_person": True,
                "jurisdiction_risk_high": False,
                "ownership_structure_complex": False,
                "screening_match_unresolved": False,
                "identity_mismatch": False,
            },
        },
    },
    {
        "name": "Refuse: unresolved screening match",
        "payload": {
            "decision_id": "kyc-4003",
            "actor_id": "kyc_analyst_1",
            "actor_role": "kyc_analyst",
            "action": "clear_kyc_case",
            "resource": "customer_profile_7930",
            "amount": None,
            "risk_score": 0.37,
            "evidence_score": 0.87,
            "jurisdiction": "US",
            "business_unit": "retail_banking",
            "override_requested": False,
            "review_case_id": "KYC-CASE-4003",
            "context": {
                "customer_id": "cust_7930",
                "screening_status": "pending_match",
                "identity_document_validated": True,
                "customer_profile_refreshed": True,
                "screening_results_current": True,
                "beneficial_owner_review_complete_if_required": True,
                "politically_exposed_person": False,
                "jurisdiction_risk_high": False,
                "ownership_structure_complex": False,
                "screening_match_unresolved": True,
                "identity_mismatch": False,
            },
        },
    },
]


def main():
    import httpx

    with httpx.Client(timeout=10.0) as client:
        for scenario in scenarios:
            response = client.post(URL, json=scenario["payload"])
            print("\n" + "=" * 72)
            print(scenario["name"])
            print(response.json())


if __name__ == "__main__":
    main()
